In [6]:
import numpy as np

In [9]:
random_arr = np.random.random()
random_arr

0.5548449608169563

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
print(arr[-1:-6:-1])

[10  9  8  7  6]


In [18]:
arr[ 0:3] = 7
arr

array([ 7,  7,  7,  4,  5,  6,  7,  8,  9, 10])

In [19]:
sum = arr.sum()
sum

70

In [20]:
average = arr.mean()
average

7.0

In [21]:
new_arr = arr[arr > average]
new_arr

array([ 8,  9, 10])

In [32]:
d_arr = ([[1,3],[5,7]])
d_arr

[[1, 3], [5, 7]]

In [33]:
d_arr[:,0]
d_arr

TypeError: list indices must be integers or slices, not tuple

In [34]:
d_arr[0, :] = 0
d_arr

TypeError: list indices must be integers or slices, not tuple